### ISSUE TITLE
Error(Happens on PMMP and forks)

### ISSUE THREAD

**Issue by asyncthreading** [JackNoordhuis/HCFSets#1]
Tesseract] [16:11:25] DEVELOPER> Enabling HCFSets v0.0.1_ALPHA
[Tesseract] [16:11:25] CRITICAL> Error: "Call to a member function setAmplifier() on null" (EXCEPTION) in "/plugins/HCFSets-master/src/hcfsets/sets/HeldItemBuffs" at line 45
[Tesseract] [16:11:25] DEVELOPER> Disabling HCFSets v0.0.1_ALPHA
[Tesseract] [16:11:25] CRITICAL> Error: "Call to a member function close() on null" (EXCEPTION) in "/plugins/HCFSets-master/src/hcfsets/Main" at line 48

When the server starts, i tryed forks and pmmp, same thing always happens.

**Comment by JackNoordhuis** [comment]
I uploaded the code to github as a resource, not a working & complete plugin. I will not be updating or completing it so don't bother opening anymore issues or spamming me to fix anything.
